language: cpp

sudo: required

compiler:
  - gcc

env:
  - QTC_SOURCE="$TRAVIS_BUILD_DIR/qt-creator-opensource-src-3.5.1" QTC_BUILD="$TRAVIS_BUILD_DIR/qtc_build/3.5.1/lib/qtcreator/" ENV_QTC_VERSION="3.5.1"

before_install:
# Qt 5.5.0 and QtC 3.4.2
  - sudo add-apt-repository -y ppa:beineri/opt-qt55
# GCC 4.9 and 7z
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install p7zip
  
# QtC sources
  - wget "http://download.qt.io/official_releases/qtcreator/3.5/3.5.1/qt-creator-opensource-src-3.5.1.tar.gz"
  - tar xzf qt-creator-opensource-src-3.5.1.tar.gz
  - wget "http://download.qt.io/snapshots/qtcreator/3.5.1/latest/installer_source/qtcreator_linux-g++-Rhel6.6-x64.7z"
  - 7zr x -o./qtc_build/3.5.1/ qtcreator_linux-g++-Rhel6.6-x64.7z

install:
  - sudo apt-get install qt55creator
  - sudo apt-get install -qq gcc-4.9 g++-4.9 
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90

before_script:
  - ls -l $TRAVIS_BUILD_DIR
  - ls -l /opt

script:
  - . /opt/qt55/bin/qt55-env.sh
  - mkdir -p build && cd build
  - export OUTPUT_PATH="$(pwd)/plugins/${ENV_QTC_VERSION}/"
  - mkdir -p "${OUTPUT_PATH}" 
  - qmake ../testplugin.pro -r -spec linux-g++ CONFIG+=release
  - make
  - find "$TRAVIS_BUILD_DIR/build/plugins"

addons:
  artifacts:
    paths:
      - ./build/plugins
